NEGATIVE = 'NEGATIVE'
NEUTRAL = 'NEUTRAL'
POSITIVE = 'POSITIVE'
API_REQUESTS_LIMIT = 450
API_REQUESTS_WINDOW = '15m'

LABELS = {
    "LABEL_0": NEGATIVE,
    "LABEL_1": NEUTRAL,
    "LABEL_2": POSITIVE,
}
